server:
  port: 8081
spring:
  application:
    name: virtual-classroom-app
  datasource:
    url: jdbc:mysql://localhost:3306/vc
    username: yash-workbench
    password: yash123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

